### ISSUE TITLE
是不是该更新了？

### ISSUE THREAD

**Issue by sing1** [gstory0404/sigmobad#1]
![image](https://github.com/gstory0404/sigmobad/assets/15246585/fed03882-af07-4475-aa0d-db8e6c53385e)

**Comment by gstory0404** [comment]
最近在逐步更新广告插件中

**Comment by sing1** [comment]
D/sigmobad_SigmobAdInterstitial(30401): ---onInterstitialAdPreLoadFail---插屏广告填充失败
D/sigmobad_SigmobAdInterstitial(30401): ---onInterstitialAdLoadError---插屏广告加载失败 { "error_code":200000, "message": sdk版本过低不支持新插屏广告类型 }


辛苦了

**Comment by gstory0404** [comment]
@sing1 已更新[v1.1.0](https://pub-web.flutter-io.cn/packages/sigmobad)
