### ISSUE TITLE
你好   这边能否打印出其他信息？

### ISSUE THREAD

**Issue by sing1** [gstory0404/sigmobad#2]
![image](https://github.com/gstory0404/sigmobad/assets/15246585/c0c0e415-3aeb-458a-9d39-53a9722509bf)

比如code之类的，目前就打印出个这无法排查原因

**Comment by gstory0404** [comment]
没有onFail回调吗，初始化时debug设为true 输出日志

**Comment by sing1** [comment]
初始化一切OK，其他几个广告也一切OK，我用原生接入，在 onSplashAdLoadFail(p0: WindAdError?, p1: String?) 打印出了p0为
{ "error_code":200000, "message":  }，这个错误码是因为没有返回广告，但是在flutter里面并没有收到任何回调，所以无法有任何感知，如果将我的设备添加到测试设备白名单每次都返回广告一切就正常，所以...没有广告的时候为什么没有收到回调呢？我看你的代码里写了。。。

**Comment by gstory0404** [comment]
sigmobad | Flutter package (pub.dev)

发布了v1.1.1 更新试试


| |

|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月29日 15:07 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [gstory0404/sigmobad] 你好 这边能否打印出其他信息？ (Issue #2) |

初始化一切OK，其他几个广告也一切OK，我用原生接入，在 onSplashAdLoadFail(p0: WindAdError?, p1: String?) 打印出了p0为
{ "error_code":200000, "message": }，这个错误码是因为没有返回广告，但是在flutter里面并没有收到任何回调，所以无法有任何感知，如果将我的设备添加到测试设备白名单每次都返回广告一切就正常，所以...没有广告的时候为什么没有收到回调呢？我看你的代码里写了。。。

**Comment by sing1** [comment]
好了，有回调了
